version: '2'
volumes:
    sense-data:
services:
  influxdb:
    build: ./influxdb
    restart: always
    volumes:
      - 'sense-data:/data'
  grafana:
    build: ./grafana
    restart: always
    ports:
      - "80:3000"
    volumes:
      - 'sense-data:/data'
    depends_on:
      - influxdb
  sensor:
    build: ./sensor
    privileged: true
    restart: always
    depends_on:
     - influxdb
  wifi-connect:
    build: ./wifi-connect
    privileged: true
    restart: always
    network_mode: host
